In [5]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [6]:
#untuk komputasi numerik
import numpy as pd

#memproses pengolahan teks
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola kata spesifik yang dicari
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

In [7]:
#import library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_row', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [8]:
df =pd.read_csv('/content/DataSetLine.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,1,2026-06-22 00:41:53,"ini line gamau perbaikin sistem loginnya nih? banyak user kehilangan akunnya loh perkara pas reinstall gak bisa masuk pake email dan password, secara jelas2 kita inget semuanya gmail akun line dan password bahkan nomor hpnya. Bukan apa-apa ya,yang udah lama pake line nih didalemnya tuh suka nyimpen data, kerjaan, foto dan bahkan akun game line!! Tapi semua dibuat sulit gabisa login, bahkan mau kirim inquiry atau login lewat web pun diarahkannya ke aplikasi lagi. tolong perhatikan ulasan pengguna"
1,Pengguna Google,1,2026-06-21 18:57:24,Masih belum bisa relog pakai no telpon. Ayok dong pihak line indo jgn nyerah upayakan ke pemerintah biar aturannya dilonggarkan. Masa apk bodong aja bisa relog by no. tlp sedangkan line platform besar gak bisa.
2,Pengguna Google,1,2026-06-21 18:04:27,"""Saya kecewa dengan sistem pemulihan akun LINE. Seharusnya nomor telepon yang masih aktif bisa membantu memulihkan akun dengan lebih mudah."
3,Pengguna Google,5,2026-06-21 15:55:52,"line please come back to indonesia, butuh bgt sm data lama. blm lg id game2 line sm sticker dah byk beli, kemrn2 di uninstal karena kebykan tmn make whatsapp tp makin kesini nyesel pake whatsapp karena ga privasy bgt nomor telp kek pintu rmh yg sell kebuka byk bet nomor tdk di kenal tiba2 chat judol ato nawarin sesuatu. jd line please come back ya"
4,Pengguna Google,1,2026-06-21 15:11:27,"This app has been experiencing errors for a long time. The News section always shows ""Temporary error, please try again later,"" and I am unable to add friends. I have tried force stopping the app, clearing the cache, restarting my phone, and changing my internet connection, but the issue remains. I also cannot log in to my old account even though it is linked to my email. Please fix these problems as soon as possible because the app is becoming unusable."

In [9]:
df['sentiment'] = df['score'].map({1.0:0, 2.0:0, 3.0:1, 4.0:1, 5.0:1})

In [10]:
#ambil teks saja untuk kita labelkan
dataku = pd.DataFrame(df[['content','sentiment']])
dataku.head(10)

,content,sentiment
0,"ini line gamau perbaikin sistem loginnya nih? banyak user kehilangan akunnya loh perkara pas reinstall gak bisa masuk pake email dan password, secara jelas2 kita inget semuanya gmail akun line dan password bahkan nomor hpnya. Bukan apa-apa ya,yang udah lama pake line nih didalemnya tuh suka nyimpen data, kerjaan, foto dan bahkan akun game line!! Tapi semua dibuat sulit gabisa login, bahkan mau kirim inquiry atau login lewat web pun diarahkannya ke aplikasi lagi. tolong perhatikan ulasan pengguna",0
1,Masih belum bisa relog pakai no telpon. Ayok dong pihak line indo jgn nyerah upayakan ke pemerintah biar aturannya dilonggarkan. Masa apk bodong aja bisa relog by no. tlp sedangkan line platform besar gak bisa.,0
2,"""Saya kecewa dengan sistem pemulihan akun LINE. Seharusnya nomor telepon yang masih aktif bisa membantu memulihkan akun dengan lebih mudah.",0
3,"line please come back to indonesia, butuh bgt sm data lama. blm lg id game2 line sm sticker dah byk beli, kemrn2 di uninstal karena kebykan tmn make whatsapp tp makin kesini nyesel pake whatsapp karena ga privasy bgt nomor telp kek pintu rmh yg sell kebuka byk bet nomor tdk di kenal tiba2 chat judol ato nawarin sesuatu. jd line please come back ya",1
4,"This app has been experiencing errors for a long time. The News section always shows ""Temporary error, please try again later,"" and I am unable to add friends. I have tried force stopping the app, clearing the cache, restarting my phone, and changing my internet connection, but the issue remains. I also cannot log in to my old account even though it is linked to my email. Please fix these problems as soon as possible because the app is becoming unusable.",0
5,"aplikasi jelek, mau login akun lama dipersulit. ga sama kayak dulu. padahal butuh banget history chat sama grub nya karena ada memories disitu. masa gua terpaksa ngerelain akun dan memories yg belum tersimpan di akun line gua?. ini lama² pengguna Lo hilang kalau kayak gini. jujur gua kecewa sih. pake kode otp aja udah cukup untuk login kok, malah ribet.",0
6,saran saya kembalikan pencarian grup chat,1
7,"apk jelek ga bisa login di akun lama, padahal akun lama tertaut di game. mau login aja ribet ga bisa pake nomer hp di negara Indonesia, masa iya harus pindah negara dulu ah elah uninstall lg aja dah ga guna",0
8,bagus untuk menambah pertemanan,1
9,"tiba² line tidak update bbrp hari. langkah yg sy lakukan, uninstall, begitu install ulang, tidak bisa login lagi, sdh pake cara yg diarahkan Line: lewat akun google/Apple, gak berhasil pdhl semua isian sdh benar. masak harus bikin akun baru? gimana dg isi dr akun lama? bisa² disalahgunakan pihak lain kalo ada yg bisa hack 🤯",0

In [11]:
my_df = dataku [['content','sentiment']]

In [12]:
#simpan dataset ke dalam file
my_df.to_csv("label_Line.csv", index = False)